language: cpp
compiler: gcc
dist: trusty
sudo: require
before_install: sudo apt-get update -qq
install: export CXX="g++-5"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
install:
- sudo apt-get install libboost-all-dev
- sudo apt-get install zlib1g-dev
- git clone https://github.com/simongog/sdsl-lite.git
- (cd sdsl-lite && sudo ./install.sh /usr/local/)
- git clone https://github.com/samtools/htslib.git
- (cd htslib && make && sudo make install)
script:
  - mkdir cmake-build-debug
  - cd cmake-build-debug
  - cmake ..
  - make
  - cd ../libgramtools/tests/
  - ./test_main
notifications:
  email: false